# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_enter_password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
